[tool.black]
line-length = 79
skip-magic-trailing-comma = true

[tool.isort]
line_length = 79
profile = "black"

[tool.poetry]
name = "route-planner"
version = "0.1.0"
description = ""
authors = ["Jacob McIntosh <nacitar.sevaht@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
isort = "^5.10.1"

[tool.poetry.dev-dependencies]
pytest = "^7.0.0"
mypy = "^0.931"
flake8 = "^4.0.1"
black = {extras = ["jupyter"], version = "^22.1.0"}
jupyter = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
