from .route import Enemy, Hit, HitType

SL1_HIT_LOOKUP: dict[str, dict[Enemy, dict[HitType, Hit]]] = {
    "Hand Axe +0": {
        Enemy.BLACK_KNIGHT_DARKROOT_BASIN: {
            HitType.WEAK_1H: Hit(10, with_rtsr=20),
            HitType.HEAVY_1H: Hit(14, with_rtsr=31),
            # HitType.JUMPING_1H: Hit(, with_rtsr=),
            HitType.WEAK_2H: Hit(16, with_rtsr=37),
            HitType.HEAVY_2H: Hit(28, with_rtsr=72),
            # HitType.JUMPING_2H: Hit(, with_rtsr=),
            HitType.BACKSTAB_1H: Hit(5 + 33, with_rtsr=8 + 90),
            HitType.BACKSTAB_2H: Hit(6 + 42, with_rtsr=10 + 116),
            HitType.RIPOSTE_1H: Hit(5 + 57, with_rtsr=8 + 146),
            HitType.RIPOSTE_2H: Hit(6 + 75, with_rtsr=10 + 179),
        }
    },
    "Reinforced Club +0": {
        Enemy.BLACK_KNIGHT_DARKROOT_BASIN: {
            HitType.WEAK_1H: Hit(15, with_rtsr=33),
            # HitType.HEAVY_1H: Hit(, with_rtsr=),
            HitType.JUMPING_1H: Hit(31, with_rtsr=82),
            HitType.WEAK_2H: Hit(28, with_rtsr=71),
            # HitType.HEAVY_2H: Hit(, with_rtsr=),
            HitType.JUMPING_2H: Hit(49, with_rtsr=134),
            HitType.BACKSTAB_1H: Hit(6 + 52, with_rtsr=11 + 138),
            HitType.BACKSTAB_2H: Hit(7 + 74, with_rtsr=14 + 177),
            HitType.RIPOSTE_1H: Hit(6 + 95, with_rtsr=11 + 209),
            HitType.RIPOSTE_2H: Hit(7 + 127, with_rtsr=14 + 263),
        }
    },
    "Reinforced Club +5": {
        Enemy.BELL_GARGOYLES: {
            HitType.WEAK_1H: Hit(84, with_rtsr=170),
            # HitType.HEAVY_1H: Hit(, with_rtsr=),
            HitType.JUMPING_1H: Hit(161, with_rtsr=275),
            HitType.WEAK_2H: Hit(185, with_rtsr=259),
            # HitType.HEAVY_2H: Hit(, with_rtsr=),
            HitType.JUMPING_2H: Hit(217, with_rtsr=358),
        },
        Enemy.OSWALD: {
            HitType.WEAK_1H: Hit(76, with_rtsr=159),
            # HitType.HEAVY_1H: Hit(, with_rtsr=),
            HitType.JUMPING_1H: Hit(150, with_rtsr=271),
            HitType.WEAK_2H: Hit(139, with_rtsr=256),
            # HitType.HEAVY_2H: Hit(, with_rtsr=333),
            HitType.JUMPING_2H: Hit(209, with_rtsr=348),
            HitType.BACKSTAB_1H: Hit(19 + 204, with_rtsr=54 + 337),
            HitType.BACKSTAB_2H: Hit(27 + 244, with_rtsr=73 + 403),
            HitType.RIPOSTE_1H: Hit(19 + 269, with_rtsr=54 + 451),
            HitType.RIPOSTE_2H: Hit(27 + 322, with_rtsr=73 + 538),
        },
        Enemy.PETRUS: {
            HitType.WEAK_1H: Hit(75, with_rtsr=157),
            # HitType.HEAVY_1H: Hit(, with_rtsr=),
            HitType.JUMPING_1H: Hit(148, with_rtsr=270),
            HitType.WEAK_2H: Hit(136, with_rtsr=254),
            # HitType.HEAVY_2H: Hit(, with_rtsr=),
            HitType.JUMPING_2H: Hit(206, with_rtsr=345),
            HitType.BACKSTAB_1H: Hit(19 + 202, with_rtsr=51 + 355),
            HitType.BACKSTAB_2H: Hit(26 + 243, with_rtsr=71 + 400),
            HitType.RIPOSTE_1H: Hit(19 + 267, with_rtsr=51 + 448),
            HitType.RIPOSTE_2H: Hit(26 + 320, with_rtsr=71 + 535),
        },
        Enemy.LAUTREC: {
            HitType.WEAK_1H: Hit(36, with_rtsr=100),
            HitType.JUMPING_1H: Hit(91, with_rtsr=208),
            # HitType.HEAVY_1H: Hit(, with_rtsr=),
            HitType.WEAK_2H: Hit(80, with_rtsr=191),
            HitType.JUMPING_2H: Hit(145, with_rtsr=295),
            # HitType.HEAVY_2H: Hit(, with_rtsr=),
            HitType.BACKSTAB_1H: Hit(12 + 146, with_rtsr=25 + 292),
            HitType.BACKSTAB_2H: Hit(15 + 189, with_rtsr=35 + 357),
            HitType.RIPOSTE_1H: Hit(12 + 220, with_rtsr=25 + 398),
            HitType.RIPOSTE_2H: Hit(15 + 276, with_rtsr=35 + 469),
        },
        Enemy.QUELAAG: {
            HitType.WEAK_1H: Hit(35, with_rtsr=96),
            # HitType.HEAVY_1H: Hit(, with_rtsr=),
            HitType.JUMPING_1H: Hit(87, with_rtsr=204),
            HitType.WEAK_2H: Hit(68, with_rtsr=166),
            # HitType.HEAVY_2H: Hit(, with_rtsr=),
            HitType.JUMPING_2H: Hit(141, with_rtsr=291),
        },
        Enemy.IRON_GOLEM: {
            HitType.WEAK_1H: Hit(29, with_rtsr=72),
            # HitType.HEAVY_1H: Hit(, with_rtsr=),
            HitType.JUMPING_1H: Hit(66, with_rtsr=175),
            HitType.WEAK_2H: Hit(59, with_rtsr=159),
            # HitType.HEAVY_2H: Hit(, with_rtsr=),
            HitType.JUMPING_2H: Hit(113, with_rtsr=257),
        },
    },
    "Battle Axe +4": {
        Enemy.BELL_GARGOYLES: {
            HitType.WEAK_1H: Hit(70, with_rtsr=130),
            HitType.HEAVY_1H: Hit(107, with_rtsr=205),
            # HitType.JUMPING_1H: Hit(, with_rtsr=),
            HitType.WEAK_2H: Hit(122, with_rtsr=226),
            HitType.HEAVY_2H: Hit(175, with_rtsr=295),
            # HitType.JUMPING_2H: Hit(, with_rtsr=),
        },
        Enemy.OSWALD: {
            HitType.WEAK_1H: Hit(59, with_rtsr=125),
            HitType.HEAVY_1H: Hit(102, with_rtsr=200),
            # HitType.JUMPING_1H: Hit(, with_rtsr=),
            HitType.WEAK_2H: Hit(116, with_rtsr=221),
            HitType.HEAVY_2H: Hit(169, with_rtsr=290),
            # HitType.JUMPING_2H: Hit(, with_rtsr=),
            HitType.BACKSTAB_1H: Hit(16 + 182, with_rtsr=45 + 303),
            HitType.BACKSTAB_2H: Hit(21 + 213, with_rtsr=60 + 468),
            HitType.RIPOSTE_1H: Hit(16 + 243, with_rtsr=45 + 405),
            HitType.RIPOSTE_2H: Hit(22 + 279, with_rtsr=60 + 468),
        },
        Enemy.PETRUS: {
            HitType.WEAK_1H: Hit(60, with_rtsr=133),
            HitType.HEAVY_1H: Hit(96, with_rtsr=193),
            # HitType.JUMPING_1H: Hit(, with_rtsr=),
            HitType.WEAK_2H: Hit(110, with_rtsr=215),
            HitType.HEAVY_2H: Hit(162, with_rtsr=287),
            # HitType.JUMPING_2H: Hit(, with_rtsr=),
            HitType.BACKSTAB_1H: Hit(15 + 176, with_rtsr=40 + 297),
            HitType.BACKSTAB_2H: Hit(20 + 208, with_rtsr=54 + 344),
            HitType.RIPOSTE_1H: Hit(15 + 241, with_rtsr=40 + 397),
            HitType.RIPOSTE_2H: Hit(20 + 274, with_rtsr=54 + 459),
        },
        Enemy.LAUTREC: {
            HitType.WEAK_1H: Hit(28, with_rtsr=149),
            HitType.HEAVY_1H: Hit(47, with_rtsr=129),
            # HitType.JUMPING_1H: Hit(, with_rtsr=),
            HitType.WEAK_2H: Hit(50, with_rtsr=149),
            HitType.HEAVY_2H: Hit(100, with_rtsr=224),
            # HitType.JUMPING_2H: Hit(, with_rtsr=),
            HitType.BACKSTAB_1H: Hit(10 + 119, with_rtsr=20 + 247),
            HitType.BACKSTAB_2H: Hit(12 + 148, with_rtsr=26 + 296),
            HitType.RIPOSTE_1H: Hit(10 + 182, with_rtsr=20 + 349),
            HitType.RIPOSTE_2H: Hit(12 + 222, with_rtsr=26 + 405),
        },
        Enemy.QUELAAG: {
            HitType.WEAK_1H: Hit(25, with_rtsr=66),
            HitType.HEAVY_1H: Hit(47, with_rtsr=130),
            # HitType.JUMPING_1H: Hit(, with_rtsr=),
            HitType.WEAK_2H: Hit(57, with_rtsr=149),
            HitType.HEAVY_2H: Hit(101, with_rtsr=225),
            # HitType.JUMPING_2H: Hit(, with_rtsr=),
        },
        Enemy.IRON_GOLEM: {
            HitType.WEAK_1H: Hit(19, with_rtsr=36),
            HitType.HEAVY_1H: Hit(28, with_rtsr=65),
            # HitType.JUMPING_1H: Hit(, with_rtsr=),
            HitType.WEAK_2H: Hit(32, with_rtsr=78),
            HitType.HEAVY_2H: Hit(51, with_rtsr=137),
            # HitType.JUMPING_2H: Hit(, with_rtsr=),
        },
    },
    "Battle Axe +3": {
        Enemy.BELL_GARGOYLES: {
            HitType.WEAK_1H: Hit(54, with_rtsr=115),
            HitType.HEAVY_1H: Hit(93, with_rtsr=184),
            # HitType.JUMPING_1H: Hit(, with_rtsr=),
            HitType.WEAK_2H: Hit(107, with_rtsr=205),
            HitType.HEAVY_2H: Hit(156, with_rtsr=268),
            # HitType.JUMPING_2H: Hit(, with_rtsr=),
        },
        Enemy.OSWALD: {
            HitType.WEAK_1H: Hit(49, with_rtsr=123),
            HitType.HEAVY_1H: Hit(88, with_rtsr=179),
            # HitType.JUMPING_1H: Hit(, with_rtsr=),
            HitType.WEAK_2H: Hit(101, with_rtsr=200),
            HitType.HEAVY_2H: Hit(150, with_rtsr=266),
            # HitType.JUMPING_2H: Hit(, with_rtsr=),
            HitType.BACKSTAB_1H: Hit(14 + 163, with_rtsr=37 + 275),
            HitType.BACKSTAB_2H: Hit(18 + 193, with_rtsr=50 + 319),
            HitType.RIPOSTE_1H: Hit(14 + 223, with_rtsr=37 + 368),
            HitType.RIPOSTE_2H: Hit(18 + 254, with_rtsr=50 + 426),
        },
        Enemy.PETRUS: {
            HitType.WEAK_1H: Hit(49, with_rtsr=117),
            HitType.HEAVY_1H: Hit(83, with_rtsr=171),
            # HitType.JUMPING_1H: Hit(, with_rtsr=),
            HitType.WEAK_2H: Hit(96, with_rtsr=193),
            HitType.HEAVY_2H: Hit(143, with_rtsr=263),
            # HitType.JUMPING_2H: Hit(, with_rtsr=),
            HitType.BACKSTAB_1H: Hit(13 + 157, with_rtsr=33 + 270),
            HitType.BACKSTAB_2H: Hit(16 + 187, with_rtsr=45 + 313),
            HitType.RIPOSTE_1H: Hit(13 + 220, with_rtsr=33 + 361),
            HitType.RIPOSTE_2H: Hit(16 + 252, with_rtsr=45 + 418),
        },
        Enemy.LAUTREC: {
            HitType.WEAK_1H: Hit(21, with_rtsr=61),
            HitType.HEAVY_1H: Hit(39, with_rtsr=110),
            # HitType.JUMPING_1H: Hit(, with_rtsr=),
            HitType.WEAK_2H: Hit(47, with_rtsr=129),
            HitType.HEAVY_2H: Hit(82, with_rtsr=196),
            # HitType.JUMPING_2H: Hit(, with_rtsr=),
            HitType.BACKSTAB_1H: Hit(9 + 102, with_rtsr=17 + 218),
            HitType.BACKSTAB_2H: Hit(10 + 128, with_rtsr=22 + 264),
            HitType.RIPOSTE_1H: Hit(9 + 159, with_rtsr=17 + 314),
            HitType.RIPOSTE_2H: Hit(10 + 196, with_rtsr=22 + 369),
        },
        Enemy.QUELAAG: {
            HitType.WEAK_1H: Hit(22, with_rtsr=55),
            HitType.HEAVY_1H: Hit(40, with_rtsr=111),
            # HitType.JUMPING_1H: Hit(, with_rtsr=),
            HitType.WEAK_2H: Hit(47, with_rtsr=129),
            HitType.HEAVY_2H: Hit(83, with_rtsr=197),
            # HitType.JUMPING_2H: Hit(, with_rtsr=),
        },
        Enemy.IRON_GOLEM: {
            HitType.WEAK_1H: Hit(17, with_rtsr=35),
            HitType.HEAVY_1H: Hit(25, with_rtsr=55),
            # HitType.JUMPING_1H: Hit(, with_rtsr=),
            HitType.WEAK_2H: Hit(28, with_rtsr=65),
            HitType.HEAVY_2H: Hit(44, with_rtsr=113),
            # HitType.JUMPING_2H: Hit(, with_rtsr=),
        },
    },
}
